import {
  generateResourcePacks,
  MinecraftVersionRange,
  PACK_DESCRIPTION,
  type Fix,
  type MinecraftVersionId,
} from "capitalisation-fixes"
import fixes from "capitalisation-fixes/src/fixes"
import "./app.css"
import { capFixesVersion, webUIVersion } from "./constants"
import { useEffect, useMemo, useState } from "preact/hooks"
import {
  fetchVersionsSummary,
  type VersionInfo,
} from "capitalisation-fixes/src/helpers/minecraftHelpers"

async function generatePackZip(
  targetVersion: MinecraftVersionId,
  targetLanguages: string[]
) {
  const zipFiles = await generateResourcePacks(fixes, {
    assets: {
      packPng: Uint8Array.from([0]),
      readme: Uint8Array.from(
        "# Some README file content!".split("").map((c) => c.charCodeAt(0))
      ),
    },
    packDescription: PACK_DESCRIPTION,
    targetLanguages,
    targetVersions: new MinecraftVersionRange({
      only: targetVersion,
    }),
  })

  if (!(targetVersion in zipFiles)) {
    console.error("Zip files generated:", zipFiles)
    throw new Error(
      `Expected zip file for version ${targetVersion}, but it was not generated`
    )
  }

  const packZip = zipFiles[targetVersion]
  packZip.file(
    "generator.txt",
    `Generated by the Capitalisation Fixes web UI v${webUIVersion} using Capitalisation Fixes v${capFixesVersion}\n`
  )
  return packZip
}

function saveFile(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob)
  const a = document.createElement("a")
  a.href = url
  a.download = filename
  a.style.display = "none"
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

async function generateAndDownloadPack() {
  const minecraftVersion = "1.21.4"
  const langs = ["en_us", "en_gb"]
  const packZip = await generatePackZip(minecraftVersion, langs)
  const blob = await packZip.generateAsync({ type: "blob" })
  saveFile(
    blob,
    `Capitalisation-Fixes-v${capFixesVersion}-${minecraftVersion}.zip`
  )
}

export function App() {
  const [versionsSummary, setVersionsSummary] = useState<null | VersionInfo[]>(
    null
  )
  const [mcVersion, setMcVersion] = useState<null | MinecraftVersionId>(null)
  const [showSnapshots, setShowSnapshots] = useState(false)
  const [includeAllFixes, setIncludeAllFixes] = useState(true)

  function versionIsRelevant(version: VersionInfo) {
    return version.type === "release" && version.data_version >= 3105 //1.19+
  }

  async function getRelevantFixes(mcVersion: MinecraftVersionId) {
    const relevantFixes = []
    for (const fix of fixes) {
      if (await fix.versions.includesVersion(mcVersion)) {
        relevantFixes.push(fix)
      }
    }
    return relevantFixes
  }
  const [relevantFixes, setRelevantFixes] = useState<null | Fix[]>(null)
  useEffect(() => {
    if (!mcVersion) return
    getRelevantFixes(mcVersion).then(setRelevantFixes)
  }, [mcVersion])

  useEffect(() => {
    fetchVersionsSummary().then((summary) => {
      setVersionsSummary(summary)
      setMcVersion(summary.filter(versionIsRelevant).at(0)?.id || null)
    })
  }, [])

  return (
    <>
      <header>
        <h1>Capitalisation Fixes</h1>
      </header>
      <main>
        <h2>Step 1: Select Minecraft version</h2>
        <select
          disabled={!versionsSummary}
          onChange={(e) =>
            e.target instanceof HTMLSelectElement
              ? setMcVersion(e.target.value)
              : console.warn("Incorrect event target")
          }
        >
          {versionsSummary &&
            versionsSummary.filter(versionIsRelevant).map((version) => (
              <option key={version.id} value={version.id}>
                {version.name}
              </option>
            ))}
        </select>
        <h2>Step 2: Choose fixes</h2>
        {(() => {
          if (!versionsSummary)
            return <p>Waiting for Minecraft versions to be loaded...</p>
          if (!mcVersion) return <p>Select a Minecraft version above first!</p>
          return (
            <>
              <p>
                <strong>{relevantFixes?.length}</strong> bugfixes are available
                for Minecraft {mcVersion}.
              </p>
              <input
                type="checkbox"
                id="include-all-fixes"
                checked={includeAllFixes}
                onChange={(e) =>
                  e.target instanceof HTMLInputElement
                    ? setIncludeAllFixes(e.target.checked)
                    : console.warn("Incorrect event target")
                }
              />
              <label htmlFor="include-all-fixes">Include all fixes</label>
              {relevantFixes?.map((fix, index) => {
                const checkboxId = `enable-fix-${index}`
                const transformerName = fix.transformer.constructor.name
                const bugLink = fix.bug ? (
                  <a
                    href={`https://bugs.mojang.com/browse/MC/issues/${fix.bug}`}
                  >
                    {fix.bug}
                  </a>
                ) : null
                return (
                  <div key={fix}>
                    <input
                      type="checkbox"
                      id={checkboxId}
                      checked
                      disabled={includeAllFixes}
                      onChange={(e) =>
                        e.target instanceof HTMLInputElement
                          ? console.warn(`${e.target} is ${e.target.checked}`)
                          : console.warn("Incorrect event target")
                      }
                    />
                    <label htmlFor={checkboxId}>
                      <code>{transformerName}</code> for <code>{fix.key}</code>
                      {bugLink && <span>(fixes {bugLink})</span>}
                    </label>
                  </div>
                )
              })}
            </>
          )
        })()}
        <h2>Step 3: Generate pack</h2>
        <p>Click the button below to generate a resource pack :)</p>
        <button onClick={generateAndDownloadPack}>
          Generate resource pack
        </button>
      </main>
    </>
  )
}
