import {
  generateResourcePacks,
  MinecraftVersionRange,
  PACK_DESCRIPTION,
} from "capitalisation-fixes"
import fixes from "capitalisation-fixes/src/fixes"
import "./app.css"
import { capFixesVersion, webUIVersion } from "./constants"

async function generatePackZip(
  targetVersion: string,
  targetLanguages: string[]
) {
  const zipFiles = await generateResourcePacks(fixes, {
    assets: {
      packPng: Uint8Array.from([0]),
      readme: Uint8Array.from(
        "# Some README file content!".split("").map((c) => c.charCodeAt(0))
      ),
    },
    packDescription: PACK_DESCRIPTION,
    targetLanguages,
    targetVersions: new MinecraftVersionRange({
      only: targetVersion,
    }),
  })

  if (!(targetVersion in zipFiles)) {
    console.error("Zip files generated:", zipFiles)
    throw new Error(
      `Expected zip file for version ${targetVersion}, but it was not generated`
    )
  }

  const packZip = zipFiles[targetVersion]
  packZip.file(
    "generator.txt",
    `Generated by the Capitalisation Fixes web UI v${webUIVersion} using Capitalisation Fixes v${capFixesVersion}\n`
  )
  return packZip
}

function saveFile(blob: Blob, filename: string) {
  const url = URL.createObjectURL(blob)
  const a = document.createElement("a")
  a.href = url
  a.download = filename
  a.style.display = "none"
  document.body.appendChild(a)
  a.click()
  document.body.removeChild(a)
  URL.revokeObjectURL(url)
}

async function generateAndDownloadPack() {
  const minecraftVersion = "1.21.4"
  const langs = ["en_us"]
  const packZip = await generatePackZip(minecraftVersion, langs)
  const blob = await packZip.generateAsync({ type: "blob" })
  saveFile(
    blob,
    `Capitalisation-Fixes-v${capFixesVersion}-${minecraftVersion}.zip`
  )
}

export function App() {
  return (
    <>
      <header>
        <h1>Capitalisation Fixes</h1>
      </header>
      <main>
        <p>Click the button below to generate a resource pack :)</p>
        <button onClick={generateAndDownloadPack}>
          Generate resource pack
        </button>
      </main>
    </>
  )
}
