name: Build each commit
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Enable Corepack
        run: corepack enable
      - name: Install dependencies using yarn
        run: yarn
      - name: Compile TypeScript source using tsc
        run: yarn build
      - name: Build the resource pack
        run: node dist/main.js
      - name: Save the built resource pack as an artifact
        uses: actions/upload-artifact@v4
        with:
          name: Resource Pack Outputs
          path: out/*.zip
          if-no-files-found: error
      - name: Print the link to the artifact
        run: 'echo "Built resource packs (one for each version) can be downloaded from: https://github.com/MMK21Hub/Capitalisation-Fixes/actions/runs/${{ github.run_id }}#artifacts (packs are inside the zip file)"'
