name: Build each commit
on: [push]
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
      - name: Install dependencies using yarn
        run: yarn
      - name: Compile TypeScript source using tsc
        run: yarn build
      - name: Build the resource pack
        run: node dist/main.js
      - name: Save the built resouce pack as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: resource-pack
          path: out/*.zip
          if-no-files-found: error